route:
  receiver: 'slack-notifications'
  group_by: [host, containers]

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#general'
    text:  "{{ .Annotations.description }}"
    api_url: 'https://hooks.slack.com/services/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'               
