global:
  # time interval for scrabing metrics from endpoints(cadvisor and node exporter)
  scrape_interval: 15s
  # time interval for evaluating rules
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with external systems
  external_labels:
     monitor: 'Containers/Host'

  # Load and evaluate rules in this file every 'evaluation_interval' seconds
  rule_files:
   - "/Prometheus/alert.rules"
# scrabing configuration for one endpoint per node

scrape_configs:

  - job_name: "node_exporter"
    scrape_interval: "5s"
    static_configs:
     - targets: ['localhost:9100']

  - job_name: "cadvisor"
    scrape_interval: "5s"
    static_configs:
     - targets: ['localhost:4194']

  - job_name: "prometheus"
    scrape_interval: "10s"
    static_configs:
     - targets: ['localhost:9090']

# Alert manager configuration
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
       - "localhost:9093"
