- hosts: PROD-VM
  sudo: yes
  tasks:

  - roles:
     - sbouii.grafana
     - sbouii.prometheus

  - name: overwrite prometheus config
    copy:
     src: ../config/prometheus/ {{ item }} 
     dest: /Prometheus/ {{ item }}
    with_items:
     - prometheus.yml
     - alert.rules
     - alertmanager_config.yml

  - name: restart alertmanager service
    systemd:
     name: alertmanager.service
     state: started
     daemon_reload: yes
     enabled: yes

  - name: restart prometheus service
    systemd:
     name: prometheus.service
     state: started
     daemon_reload: yes
     enabled: yes

  - name: create cadvisor directory
    file:
     path: /Cadvisor
     state: directory
     mode: 755

  - name: install cadvisor
    unarchive:
     src: https://github.com/google/cadvisor/releases/download/v0.20.5/cadvisor
     dest: /Cadvisor
     copy: no
   
  - name: run cadvisor
    shell: ./cadvisor 
