- hosts: PROD-VM
  sudo: yes
  pre_tasks:
  - name: download grafana role
    git:
     repo: 'https://github.com/sbouii/grafana-ansible.git'
     dest: /etc/ansible/roles
     
  - name: download prometheus role
    git:
     repo: 'https://github.com/sbouii/prometheus-ansible.git'
     dest: /etc/ansible/roles
    
#  roles:
#   - sbouii.grafana
#   - sbouii.prometheus
  tasks:

  - name: overwrite prometheus config
    copy:
      src: ../config/prometheus/{{ item }} 
      dest: /Prometheus/{{ item }}
    with_items:
     - prometheus.yml
     - alert.rules
     - alertmanager_config.yml

  - name: restart alertmanager service
    systemd:
     name: alertmanager.service
     state: restarted
     daemon_reload: yes
     enabled: yes

  - name: restart prometheus service
    systemd:
     name: prometheus.service
     state: restarted
     daemon_reload: yes
     enabled: yes

  - name: create cadvisor directory
    file:
     path: /Cadvisor
     state: directory

  - name: install cadvisor
    get_url:
     url:  https://github.com/manics/cadvisor/releases/download/v0.25.0-manics1/cadvisor
     checksum: sha256:a3a11c85024a295c14ab3a066420475d66203c54fe40a852dac8f3a10cb43161
     dest: /Cadvisor/cadvisor-0.25.0
     force: no   
     
  - name: add cadvisor init service 
    copy:
     src: ../config/cadvisor/cadvisor.service
     dest: /etc/systemd/system/cadvisor.service

  - name: restart cadvisor service
    systemd:
     name: cadvisor.service
     state: restarted
     daemon_reload: yes
     enabled: yes  

  - name: set up postgres docker containers
    docker:
     name: postgres-container
     image: postgres
     state: started
     count: 2
     expose:
      - 5432
      
