- hosts: PROD-VM
  sudo: yes
  roles:
   - sbouii.grafana
   - sbouii.prometheus
  tasks:

  - name: overwrite prometheus config
    copy:
      src: ../config/prometheus/{{ item }} 
      dest: /Prometheus/{{ item }}
    with_items:
     - prometheus.yml
     - alert.rules
     - alertmanager_config.yml

  - name: restart alertmanager service
    systemd:
     name: alertmanager.service
     state: restarted
     daemon_reload: yes
     enabled: yes

  - name: restart prometheus service
    systemd:
     name: prometheus.service
     state: restarted
     daemon_reload: yes
     enabled: yes

  - name: create cadvisor directory
    file:
     path: /Cadvisor
     state: directory

  - name: install cadvisor
    get_url:
     url:  https://github.com/manics/cadvisor/releases/download/v0.25.0-manics1/cadvisor
     checksum: sha256:a3a11c85024a295c14ab3a066420475d66203c54fe40a852dac8f3a10cb43161
     dest: /Cadvisor/cadvisor-0.25.0
     force: no
   
<<<<<<< HEAD
  - name: run cadvisor
    shell: ./cadvisor

  - name: set up docker containers
    docker:
     name: postgres-container
     image: 
     state: started
     count: 2
     expose:
      - 
     
 
=======
  - name: add cadvisor init service 
    copy:
     src: ../config/cadvisor/cadvisor.service
     dest: /etc/systemd/system/cadvisor.service

  - name: restart cadvisor service
    systemd:
     name: cadvisor.service
     state: restarted
     daemon_reload: yes
     enabled: yes
  
>>>>>>> 226ccbc1e0f7c8f4daa30fd2d895ba28ff7c25fb
